# Generated by Django 6.0.4 on 2026-05-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='neutral_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choix',
            name='style',
            field=models.CharField(choices=[('VISUEL', 'Visuel'), ('AUDITIF', 'Auditif'), ('KINESTHESIQUE', 'Kinesthesique'), ('NEUTRE', 'Neutre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='style_dominant',
            field=models.CharField(choices=[('VISUEL', 'Visuel'), ('AUDITIF', 'Auditif'), ('KINESTHESIQUE', 'Kinesthesique'), ('NEUTRE', 'Neutre')], max_length=20),
        ),
    ]
