# Generated by Django 6.0.4 on 2026-05-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_resultat_neutral_count_alter_choix_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='profil_type',
            field=models.CharField(choices=[('DOMINANT', 'Style dominant clair'), ('MIXTE', 'Profil mixte'), ('EQUILIBRE', 'Profil equilibre')], default='DOMINANT', max_length=20),
        ),
    ]
